Repository cardbox/frontend, pull requests merged in 2021-08, with the labels that each got.

#56 BOX-185: Доприкрутил API вместо mock-заглушек [part 2] [final]
  openapi.config.js
  src/api/internal/index.gen.ts
  src/api/internal/index.ts
  src/api/types.ts
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/entities/session/index.ts
  src/entities/session/model.ts
  src/entities/user/model/index.ts
  src/entities/user/types.ts
  src/entities/user/ui/user-card.tsx
  src/entities/user/ui/user-preview-list.tsx
  src/entities/user/ui/user-preview.tsx
  src/entities/viewer/lib.ts
  src/features/search-bar/models/index.ts
  src/pages/card/view/index.tsx
  src/pages/card/view/model.ts
  src/pages/comments/comments.tsx
  src/pages/home/index.tsx
  src/pages/home/model.ts
  src/pages/oauth-done/model.ts
  src/pages/search/page.tsx
  src/pages/user/index.tsx
  src/pages/user/model.ts
  src/pages/user/skeleton.tsx
  src/shared/assets/index.ts
  src/shared/assets/logo.png
  src/ui/atoms/skeleton.tsx
  typings/index.d.ts
Labels: Frontend, Refactoring

#58 BOX-179: Refine UIKit implementation and API usage
  src/entities/card/organisms/card-preview.tsx
  src/entities/session/molecules/session-panel.tsx
  src/entities/user/ui/user-card.tsx
  src/entities/user/ui/user-preview.tsx
  src/features/card/draft/ui/atoms/reset-changes.tsx
  src/features/card/draft/ui/atoms/submit-changes.tsx
  src/features/card/draft/ui/molecules/index.tsx
  src/features/search-bar/organisms/search-bar.tsx
  src/pages/card/edit/index.tsx
  src/pages/card/view/index.tsx
  src/pages/home/index.tsx
  src/pages/search/page.tsx
  src/pages/user/index.tsx
  src/pages/user/skeleton.tsx
  src/ui/atoms/button.tsx
  src/ui/atoms/empty.tsx
  src/ui/atoms/index.ts
  src/ui/atoms/text.tsx
  src/ui/molecules/index.ts
  src/ui/molecules/tabs/index.ts
  src/ui/molecules/tabs/tab.tsx
  src/ui/molecules/tabs/tabs.tsx
  src/ui/molecules/tabs/title.tsx
  src/ui/templates/index.ts
Labels: Frontend, Refactoring, Legacy

#62 BOX-150 (features/card): adds tags for cards
  src/app/application.tsx
  src/features/card/draft/model.ts
  src/features/card/draft/ui/atoms/index.ts
  src/features/card/draft/ui/atoms/tag-input.tsx
  src/features/card/draft/ui/atoms/tags.tsx
  src/features/card/draft/ui/molecules/index.tsx
  src/features/search-bar/molecules/search.tsx
  src/lib/theme.ts
  src/lib/todo.ts
  src/pages/card/create/model.ts
  src/pages/user/index.tsx
  src/ui/atoms/button.tsx
  src/ui/atoms/empty.tsx
  src/ui/atoms/index.ts
  src/ui/atoms/input.tsx
  src/ui/icons/add.svg
  src/ui/icons/close.svg
  src/ui/icons/index.ts
  src/ui/molecules/chip.tsx
  src/ui/molecules/index.ts
  src/ui/molecules/tabs/title.tsx
  yarn.lock
Labels: feature, fix
