Repository cardbox/frontend, pull requests merged in 2021-11, with the labels that each got.

#73 BOX-202 Add adaptive
  .babelrc.js
  src/app/application.tsx
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/entities/user/ui/user-card.tsx
  src/features/search-bar/organisms/search-bar.tsx
  src/pages/card/view/page.tsx
  src/pages/home/page.tsx
  src/pages/user/page.tsx
  src/pages/user/skeleton.tsx
  src/shared/lib/breakpoints.ts
  src/shared/ui/atoms/text.tsx
  src/shared/ui/atoms/toast.tsx
  src/shared/ui/templates/content-centered.tsx
  src/shared/ui/templates/paper-container.ts
Labels: Frontend, Improvement

#87 BOX-257 Add avatar for session-panel
  src/entities/session/molecules/session-panel.tsx
  src/pages/oauth-done/model.ts
  src/shared/api/internal/index.gen.ts
Labels: feature

#88 BOX-258 Возвращать на просматриваемую страницу после логина
  src/pages/oauth-done/model.ts
Labels: feature

#84 BOX-94 BOX-237 Add ability to add/remove card to favorites
  openapi.config.js
  src/entities/card/model/index.ts
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/features/card/draft/model.ts
  src/pages/card/edit/model.ts
  src/pages/card/view/model.ts
  src/pages/card/view/page.tsx
  src/pages/home/model.ts
  src/pages/home/page.tsx
  src/pages/search/model.ts
  src/pages/user/model.ts
  src/pages/user/page.tsx
  src/shared/api/internal/index.gen.ts
  src/shared/api/types.ts
Labels: Frontend, Defect
