Repository cardbox/frontend, pull requests merged in 2021-07, with the labels that each got.

#37 BOX-137 fix letter duplicate for user search page
  src/entities/user/organisms/user-preview.tsx
  yarn.lock
Labels: bug, fix

#27 BOX-60 BOX-26 User page and card view page
  src/app/application.tsx
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/features/search-bar/organisms/search-bar.tsx
  src/pages/card/index.tsx
  src/pages/user/index.tsx
  src/shared/constants.ts
  src/ui/atoms/button.tsx
  src/ui/icons/default_userlogo.svg
  src/ui/icons/index.ts
  src/ui/icons/like.svg
  src/ui/icons/user_bg.svg
  src/ui/index.ts
  src/ui/molecules/index.ts
  src/ui/molecules/tab.tsx
  src/ui/molecules/tabs.tsx
  src/ui/molecules/title.tsx
Labels: feature

#41 BOX-136 Remove pr-labeler
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
Labels: Infrastructure

#44 feature/BOX-139: add link to user(author) page
  src/api/mock/fixtures.ts
  src/app/application.tsx
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/entities/user/organisms/user-preview-list.tsx
  src/entities/user/organisms/user-preview.tsx
  src/features/search-bar/organisms/search-bar.tsx
  src/pages/card/index.tsx
  src/pages/comments/comments.tsx
  src/pages/home/index.tsx
  src/pages/search/page.tsx
  src/pages/user/index.tsx
  src/ui/organisms/user-card.tsx
Labels: Пользователь, Просмотр

#43 BOX-97: Implement CardEdit logic
  package.json
  src/api/internal/index.ts
  src/api/mock/fixtures.ts
  src/api/mock/index.ts
  src/api/types.ts
  src/entities/card/model/index.ts
  src/entities/card/organisms/card-list.tsx
  src/entities/card/organisms/card-preview.tsx
  src/features/card/draft/README.md
  src/features/card/draft/index.ts
  src/features/card/draft/model.ts
  src/features/card/draft/ui/edit-content.tsx
  src/features/card/draft/ui/edit-title.tsx
  src/features/card/draft/ui/index.ts
  src/features/card/draft/ui/reset-changes.tsx
  src/features/card/draft/ui/submit-changes.tsx
  src/lib/fp.ts
  src/pages/card/README.md
  src/pages/card/edit/index.tsx
  src/pages/card/edit/model.ts
  src/pages/card/view/index.tsx
  src/pages/card/view/model.ts
  src/pages/paths.ts
  src/pages/routes.ts
  src/ui/atoms/button.tsx
  src/ui/atoms/skeleton.tsx
  yarn.lock
Labels: Frontend
