Repository cardbox/frontend, pull requests merged in 2021-10, with the labels that each got.

#70 BOX-216: Fix tags crashing
  package.json
  src/features/card/draft/ui/atoms/tag-input.tsx
  src/features/card/draft/ui/atoms/tags.tsx
  yarn.lock
Labels: Frontend, Defect

#66 BOX-156 fix view of the not found card 404 page
  src/index.ts
  src/pages/card/edit/page.tsx
  src/pages/card/view/page.tsx
  src/pages/home/page.tsx
  src/shared/ui/atoms/empty.tsx
Labels: Frontend, Defect

#75 BOX-233 Add link to More in message line
  src/pages/home/page.tsx
Labels: Defect

#74 BOX-220: Added TT Hover fonts
  src/app/application.tsx
  src/app/styles/global-fonts.ts
  src/shared/assets/fonts/TT_Hoves_Black.woff2
  src/shared/assets/fonts/TT_Hoves_Black_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Bold.woff2
  src/shared/assets/fonts/TT_Hoves_Bold_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_DemiBold.woff2
  src/shared/assets/fonts/TT_Hoves_DemiBold_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_ExtraBold.woff2
  src/shared/assets/fonts/TT_Hoves_ExtraBold_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_ExtraLight.woff2
  src/shared/assets/fonts/TT_Hoves_ExtraLight_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Hairline.woff2
  src/shared/assets/fonts/TT_Hoves_Hairline_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Light.woff2
  src/shared/assets/fonts/TT_Hoves_Light_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Medium.woff2
  src/shared/assets/fonts/TT_Hoves_Medium_Italic.woff2
  src/shared/assets/fonts/TT_Hoves_Regular.woff2
  src/shared/assets/fonts/TT_Hoves_Thin.woff2
  src/shared/assets/fonts/TT_Hoves_Thin_Italic.woff2
  src/shared/ui/atoms/text.tsx
  typings/index.d.ts
Labels: Frontend, Improvement

#76 BOX-241: Rename font, change method to include it
  src/app/application.tsx
  src/app/styles/global-fonts.ts
  src/shared/ui/atoms/text.tsx
Labels: Frontend, Defect

#77 BOX-223 fix link to user from card view page
  src/entities/user/ui/user-card.tsx
  src/pages/card/view/page.tsx
Labels: Frontend, Defect

#78 BOX-229 allow to create card only for authenticated
  package.json
  src/entities/session/accesso.ts
  src/entities/session/index.ts
  src/entities/session/molecules/index.ts
  src/entities/session/molecules/session-panel.tsx
  src/entities/session/molecules/show-only.tsx
  src/entities/session/only-hooks.ts
  src/features/search-bar/organisms/search-bar.tsx
  src/pages/card/create/model.ts
  yarn.lock
Labels: Frontend, Defect

#85 BOX-227: Add actual edit-permissions check
  src/pages/card/edit/model.ts
Labels: Frontend, Defect

#86 BOX-242 Logout/Profile row enhancements
  src/entities/session/model/session.ts
  src/entities/session/molecules/session-panel.tsx
Labels: Frontend
